
steps:
  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '14.18.1'
  - task: UsePythonVersion@0
    displayName: 'Install Python 2.x'
    inputs:
      versionSpec: '2.x'

  - script: npm install
  - script: npm test
  - script: npm run-script pack
  - task: PublishBuildArtifacts@1

